<?binding.jca ExampleDatabaseSelectAdapter_db.jca?>
<wsdl:definitions name="ExampleDatabaseSelectAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MediatorExamples/LogProcessor/ExampleDatabaseSelectAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MediatorExamples/LogProcessor/ExampleDatabaseSelectAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ExampleDatabaseSelectAdapter">
    <plt:partnerLinkType name="ExampleDatabaseSelectAdapter_plt">
        <plt:role name="ExampleDatabaseSelectAdapter_role">
            <plt:portType name="tns:ExampleDatabaseSelectAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ExampleDatabaseSelectAdapter" schemaLocation="xsd/ExampleDatabaseSelectAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ExampleDatabaseSelectAdapterSelect_inputParameters">
        <wsdl:part name="ExampleDatabaseSelectAdapterSelect_inputParameters" element="top:ExampleDatabaseSelectAdapterSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="LogsCollection_msg">
        <wsdl:part name="LogsCollection" element="top:LogsCollection"/>
    </wsdl:message>
    <wsdl:portType name="ExampleDatabaseSelectAdapter_ptt">
        <wsdl:operation name="ExampleDatabaseSelectAdapterSelect">
            <wsdl:input message="tns:ExampleDatabaseSelectAdapterSelect_inputParameters"/>
            <wsdl:output message="tns:LogsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
