<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../DatabaseMediator.wsdl"/>
      <rootElement name="LogsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ExampleDatabaseAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ExampleDatabaseAdapter.wsdl"/>
      <rootElement name="LogsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ExampleDatabaseAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE APR 14 18:47:01 CEST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://xmlns.oracle.com/MediatorExamplesGithubApplication/LogProcessor_Example3_dynamic_routes/DatabaseMediator"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/MediatorExamples/LogProcessor/ExampleDatabaseAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:inp1="http://xmlns.oracle.com/pcbpel/adapter/db/top/ExampleDatabaseAdapter"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns xsd wsdl inp1 ns0 plt bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <inp1:LogsCollection>
      <xsl:for-each select="/inp1:LogsCollection/inp1:Logs">
        <inp1:Logs>
          <inp1:id>
            <xsl:if test="inp1:id/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="inp1:id/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="inp1:id"/>
          </inp1:id>
          <xsl:if test="inp1:fecha">
            <inp1:fecha>
              <xsl:if test="inp1:fecha/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="inp1:fecha/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="inp1:fecha"/>
            </inp1:fecha>
          </xsl:if>
          <xsl:if test="inp1:mensaje">
            <inp1:mensaje>
              <xsl:if test="inp1:mensaje/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="inp1:mensaje/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="inp1:mensaje"/>
            </inp1:mensaje>
          </xsl:if>
        </inp1:Logs>
      </xsl:for-each>
    </inp1:LogsCollection>
  </xsl:template>
</xsl:stylesheet>
