<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../LogWebservice.wsdl"/>
      <rootElement name="log" namespace="http://www.example.org/LogWebservice"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ExampleFileAdapter.wsdl"/>
      <rootElement name="log" namespace="http://www.example.org/LogWebservice"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [FRI APR 10 09:04:24 CEST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:inp1="http://www.example.org/LogWebservice"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns="http://oracle.com/sca/soapservice/MediatorExamples/LogProcessor/LogWebservice"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/file/MediatorExamples/LogProcessor/ExampleFileAdapter"
                xmlns:xlog="http://xmlns.oracle.com/pcn/funcLog"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl inp1 tns wsdl xsd plt ns0 jca bpws xp20 bpel bpm ora socket xlog mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <inp1:log>
      <inp1:logMessage>
        <inp1:date>
          <xsl:value-of select="/inp1:log/inp1:logMessage/inp1:date"/>
        </inp1:date>
        <inp1:logLevel>
          <xsl:value-of select="/inp1:log/inp1:logMessage/inp1:logLevel"/>
        </inp1:logLevel>
        <inp1:message>
          <xsl:value-of select="/inp1:log/inp1:logMessage/inp1:message"/>
        </inp1:message>
      </inp1:logMessage>
    </inp1:log>
  </xsl:template>
</xsl:stylesheet>
